openapi: 3.0.0
info:
  description: Pollenisator index api file
  version: 1.2.0
  title: Swagger REST Article

paths:
  '/auth/getModuleInfo':
    get:
      summary: get module info
      operationId: pollenisator.server.modules.Auth.auth.getModuleInfo
      responses:
        '200':
          description: OK
      description: get module info
  '/auth/{pentest}':
    post:
      summary: insert authentication inf
      operationId: pollenisator.server.modules.Auth.auth.insert
      responses:
        '200':
          description: OK
      description: Add an authentication info
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthInfo'
        description: ''
      tags:
        - Authentication Info
    parameters:
      - schema:
          type: string
        name: pentest
        in: path
        required: true
        description: pentest name

  '/auth/{pentest}/{auth_iid}/link/{object_iid}':
    post:
      summary: link an existing auth info to an object in db
      operationId: pollenisator.server.modules.Auth.auth.link
      responses:
        '200':
          description: OK
      description: link an existing auth info to an object in db
      tags:
        - Authentication Info
    parameters:
      - schema:
          type: string
        name: pentest
        in: path
        required: true
        description: pentest name
      - schema:
          type: string
        name: object_iid
        in: path
        required: true
        description: object_iid to link to
      - schema:
          type: string
        name: auth_iid
        in: path
        required: true
        description: auth_iid object to link

components:
  schemas:
    AuthInfo:
      title: Authentication Information
      type: object
      properties:
        name:
          type: string
        value:
          type: string
        type:
          type: string
          enum: [password, hash, cookie]
      required:
        - name
        - value
        - type