openapi: 3.0.0
info:
  description: Pollenisator index api file
  version: 1.2.0
  title: Swagger REST Article

paths:

  '/cheatsheet/':
    post:
      summary: insert cheatsheet item
      operationId: pollenisator.server.modules.cheatsheet.cheatsheet.insert
      responses:
        '200':
          description: OK
      description: Add an cheatsheet item
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckItem'
        description: ''
      tags:
        - Cheatsheet
  '/cheatsheet/{iid}':
    parameters:
      - schema:
          type: string
        name: iid
        in: path
        required: true
        description: CheckItem iid
    delete:
      tags:
        - Cheatsheet
      summary: Delete check item
      operationId: pollenisator.server.modules.cheatsheet.cheatsheet.delete
      responses:
        '200':
          description: OK
      description: Delete check item
    put:
      summary: ''
      tags:
        - Cheatsheet
      operationId: pollenisator.server.modules.cheatsheet.cheatsheet.update
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckItem'

  '/cheatsheet/{pentest}':
    parameters:
      - schema:
          type: string
        name: pentest
        in: path
        required: true
    post:
      summary: insert checkinstance item
      operationId: pollenisator.server.modules.cheatsheet.checkinstance.insert
      responses:
        '200':
          description: OK
      description: Add an checkItem instance item
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckInstance'
        description: ''
      tags:
        - Cheatsheet
  '/cheatsheet/{pentest}/getTargetRepr':
    parameters:
      - schema:
          type: string
        name: pentest
        in: path
        required: true
    post:
      tags:
        - Cheatsheet
      summary: get a string representation of the check instance target
      operationId: pollenisator.server.modules.cheatsheet.checkinstance.getTargetRepr
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
      description: 'get a string representation of the check instance target'
      responses:
        '200':
          description: a list of targets representation string in same order as iids list
  '/cheatsheet/{pentest}/{iid}':
    parameters:
      - schema:
          type: string
        name: pentest
        in: path
        required: true
      - schema:
          type: string
        name: iid
        in: path
        required: true
        description: Check instance iid
    delete:
      tags:
        - Cheatsheet
      summary: Delete check item
      operationId: pollenisator.server.modules.cheatsheet.checkinstance.delete
      responses:
        '200':
          description: OK
      description: Delete checkinstance item
    get:
      tags:
        - Cheatsheet
      summary: Get check instance informations
      operationId: pollenisator.server.modules.cheatsheet.checkinstance.getInformations
      responses:
        '200':
          description: OK
      description: Delete checkinstance item
    post:
      summary: "Apply the checkitem to the pentest"
      tags:
        - Cheatsheet
      operationId: pollenisator.server.modules.cheatsheet.cheatsheet.applyToPentest
      responses:
        '200':
          description: OK
    put:
      summary: ''
      tags:
        - Cheatsheet
      operationId: pollenisator.server.modules.cheatsheet.checkinstance.update
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckInstance'

  "/cheatsheet/find":
    post:
      operationId: pollenisator.server.modules.cheatsheet.cheatsheet.find
      tags:
        - Cheatsheet
      summary: "find check items"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pipeline:
                  type: string
                  example: "{}"
      responses:
        "200":
          description: successful find command with parameters
          content:
            application/json:
              examples:
                success:
                  value: '[{"_id": "60a3aaa129926f9ad7197919", "parent": "ObjectId|60a3aaa129926f9ad7197915",  "scope": "test",   "wave": "Testina" },  { "_id": "60f58598d8357e0f40e7fa66","scope": "test.fr" }]'
    

components:
  schemas:
    CheckInstance:
      title: CheckInstance
      type: object
      description: Checklist item instance
      properties:
        check_iid:
          type: string
        target_iid:
          type: string
        target_type:
          type: string
        status:
          type: string
        notes:
          type: string
        

    CheckItem:
      title: CheckItem
      type: object
      description: Checklist item
      properties:
        title:
          type: string
        lvl:
          type: string
        ports:
          type: string
        priority:
          type: integer
          minimum: 0
          maximum: 99
        max_thread:
          type: integer
        description:
          type: string
        check_type:
          type: string
          enum: [manual_commands, auto_commands, script, manual]
        step:
          type: integer
        parent: 
          type: string
          nullable: true
        commands:
          type: array
          items:
            type: string
        defect_tags:
          type: array
          items:
            type: array
            items:
              type: string          
        script:
          type: string
        pentest_types:
          type: array
          items:
            type: string
        category:
          type: string
        defects:
          type: array
          items:
            type: string


