openapi: 3.0.0
info:
  description: Pollenisator index api file
  version: 1.2.0
  title: Swagger REST Article

paths:
  '/cheatsheet/getModuleInfo':
    get:
      tags:
        - Cheatsheet
      summary: get module info
      operationId: pollenisator.server.modules.Cheatsheet.cheatsheet.getModuleInfo
      responses:
        '200':
          description: OK
      description: get module info
  '/cheatsheet/':
    post:
      summary: insert cheatsheet item
      operationId: pollenisator.server.modules.Cheatsheet.cheatsheet.insert
      responses:
        '200':
          description: OK
      description: Add an cheatsheet item
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckItem'
        description: ''
      tags:
        - Cheatsheet
  '/cheatsheet/{iid}':
    parameters:
      - schema:
          type: string
        name: iid
        in: path
        required: true
        description: CheckItem iid
    delete:
      tags:
        - Cheatsheet
      summary: Delete check item
      operationId: pollenisator.server.modules.Cheatsheet.cheatsheet.delete
      responses:
        '200':
          description: OK
      description: Delete check item
    put:
      summary: ''
      tags:
        - Cheatsheet
      operationId: pollenisator.server.modules.Cheatsheet.cheatsheet.update
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckItem'

  '/cheatsheet/{pentest}':
    parameters:
      - schema:
          type: string
        name: pentest
        in: path
        required: true
    post:
      
      summary: insert checkinstance item
      operationId: pollenisator.server.modules.Cheatsheet.checkinstance.insert
      responses:
        '200':
          description: OK
      description: Add an checkItem instance item
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckInstance'
        description: ''
      tags:
        - Cheatsheet
  '/cheatsheet/{pentest}/{iid}':
    parameters:
      - schema:
          type: string
        name: pentest
        in: path
        required: true
      - schema:
          type: string
        name: iid
        in: path
        required: true
        description: Check instance iid
    delete:
      tags:
        - Cheatsheet
      summary: Delete check item
      operationId: pollenisator.server.modules.Cheatsheet.checkinstance.delete
      responses:
        '200':
          description: OK
      description: Delete checkinstance item
    get:
      tags:
        - Cheatsheet
      summary: Get check instance informations
      operationId: pollenisator.server.modules.Cheatsheet.checkinstance.getInformations
      responses:
        '200':
          description: OK
      description: Delete checkinstance item
    put:
      summary: ''
      tags:
        - Cheatsheet
      operationId: pollenisator.server.modules.Cheatsheet.checkinstance.update
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckInstance'

  

components:
  schemas:
    CheckInstance:
      title: CheckInstance
      type: object
      description: Checklist item instance
      properties:
        check_iid:
          type: string
        status:
          type: string
        notes:
          type: string
        

    CheckItem:
      title: CheckItem
      type: object
      description: Checklist item
      properties:
        title:
          type: string
        description:
          type: string
        check_type:
          type: string
          enum: [manual_commands, auto_commands, script, manual]
        step:
          type: integer
        parent: 
          type: string
          nullable: true
        commands:
          type: array
          items:
            type: string
        script:
          type: string
        pentest_types:
          type: array
          items:
            type: string
        category:
          type: string
        defects:
          type: array
          items:
            type: string


