openapi: 3.0.0
info:
  description: Pollenisator index api file
  version: 1.2.0
  title: Swagger REST Article

paths:
  "/utils/textcompletion/status":
    get:
      operationId: pollenisator.server.modules.utils.utils.textcompletion_status
      tags:
        - Utils
      summary: Get text completion status
      responses:
        "200":
          description: Successfully return text completion status
          content:
            application/json:
              examples:
                Success:
                  value: '{"status": "ready"}'
                Unavailable:
                  value: '{"status": "unavailable"}'
  "/utils/textcompletion":
    post:
      operationId: pollenisator.server.modules.utils.utils.textcompletion
      tags:
        - Utils
      summary: Text autocomplete
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                model:
                  type: string
      responses:
        "200":
          description: Successfully return completed text
          content:
            application/json:
              examples:
                Success:
                  value: '{"completed_text": "Response to the request"}'
       