# coding: utf-8

from __future__ import absolute_import
from pollenisator.server.ServerModels.Element import ServerElement

class ShareFile(ServerElement):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, valuesFromDb=None):
        if valuesFromDb is None:
            valuesFromDb = {}
        self.initialize(valuesFromDb.get("path"), valuesFromDb.get("flagged"), valuesFromDb.get("size") , valuesFromDb.get("users") )

    def initialize(self, path=None, flagged=None, size=None,  users=None): 
        self.path = path
        self.flagged = flagged
        self.size = size
        self.users = users if users is not None else []
        return self

    def getData(self):
        return {"flagged": self.flagged, "path":self.path, "size":self.size,
                 "users":self.users}

    def add_user(self, domain, user, priv):
        users = set(self.users)
        users.add((domain, user, priv))
        self.users = list(users)
