"""A plugin to parse a CrackMapExex scan"""

import re

from pollenisator.core.components.tag import Tag
from pollenisator.core.models.ip import Ip
from pollenisator.core.models.port import Port

from pollenisator.server.modules.activedirectory.users import User
from pollenisator.plugins.plugin import Plugin
from pollenisator.plugins.plugin_result import PluginResult, InfoUpdate, TagAddition, UserLink, ObjectUpdate

def remove_term_colors(data: str) -> str:
    """
    Remove terminal colors from a string
    Args:
        data: the string to remove colors from
    Returns:
        string: the string without colors
    """
    return re.sub(r'\x1b\[[0-9;]+[a-zA-Z]', '', data)

def getInfos(cme_file):
    r"""Read the given cme output file results and return a dictionnary with ips and a list of their open ports and infos.
        Args:
            cme_file:  the path to the .txt file generated by an cme.
        Returns:
        A tupe with 3 values:
            0. A List with dictionnaries inside.
                 Each dictionnary holds : "ip":str, "port":str, "hostname":str, "notes":str, "powned":bool
            1. a count of Powned found
            2. additional notes

    File example:

EMPTY :
\x1b[1m\x1b[34mSMB\x1b[0m          10.10.11.152    445    DC01             [1m[34m[*][0m Windows 10.0 Build 17763 x64 (name:DC01) (domain:timelapse.htb) (signing:True) (SMBv1:False)

POWNED EXEMPLE:
\x1b[1m\x1b[34mSMB\x1b[0m          10.10.10.254:445 HAGRID          \x1b[1m\x1b[34m[*]\x1b[0m Windows 6.3 Build 9600 (name:HAGRID) (domain:POUDLARD)
\x1b[1m\x1b[34mSMB\x1b[0m          10.10.10.254:445 HAGRID          \x1b[1m\x1b[32m[+]\x1b[0m POUDLARD\Administrateur:Algo_LAB_2012* \x1b[1m\x1b[33m(Pwn3d!)\x1b[0m
\x1b[1m\x1b[34m[*]\x1b[0m KTHXBYE!

NOT POWNED:
\x1b[1m\x1b[34mSMB\x1b[0m          10.10.10.11:445 DOBBY-PC        \x1b[1m\x1b[34m[*]\x1b[0m Windows 6.1 Build 0 (name:DOBBY-PC) (domain:POUDLARD)
\x1b[1m\x1b[34mSMB\x1b[0m          10.10.10.254:445 HAGRID          \x1b[1m\x1b[34m[*]\x1b[0m Windows 6.3 Build 9600 (name:HAGRID) (domain:POUDLARD)
\x1b[1m\x1b[34m[*]\x1b[0m KTHXBYE!

\x1b[1m\x1b[34mSMB\x1b[0m          10.10.11.152    445    DC01             [1m[34m[*][0m Windows 10.0 Build 17763 x64 (name:DC01) (domain:timelapse) (signing:True) (SMBv1:False)
\x1b[1m\x1b[34mSMB\x1b[0m         10.10.11.152    445    DC01             [1m[35m[-][0m timelapse\admin:admin STATUS_ACCESS_DENIED 

SMB         winterfell.north.sevenkingdoms.local 445    WINTERFELL       [-] north.sevenkingdoms.local\brandon.stark account vulnerable to asreproast attack 

"""
    result = {}
    retour = []
    regex_info = re.compile(r"(?:LDAP|SMB)\s+(\S+)\s+(\d+)\s+\S+\s+\[\*\]\s*([^\(]+)\(name:(.*)\) \(domain:(.*)\) \(signing:(True|False)\) \(SMBv1:(False|True)\)$", re.MULTILINE)
    regex_logon_failed = re.compile(
        r"(?:LDAP|SMB)\s+(\S+)\s+(\d+)\s+(\S+)\s+\[\-\]\s*([^\\]+)\\([^:\n]+):(.*?) ([A-Z_]+)$", re.MULTILINE)
    regex_success = re.compile(
        r"(?:LDAP|SMB)\s+(\S+)(?:\s+|:)(\d+)\s+(\S+)\s+\[\+\]\s*([^\\]+)\\([^:]+):(.*?)($|\(\S+\))$", re.MULTILINE)
    regex_module_lsassy = re.compile(r"^LSASSY\s+(\S+)\s+(\d+)\s+(\S+)\s+([^\\]+)\\(\S+)\s+(\S+)$")
    regex_module_secrets = re.compile(r"^(?:SMB|LDAP)\s+(\S+)\s+(\d+)\s+(\S+)\s+(?!\[.\])(\S.+)$")
    regex_module_asproast = re.compile(r"^(?:LDAP|SMB)\s+(\S+)\s+(\d+)\s+(\S+)\s+\[[-+]\] ([^\\]+)\\([^:]+) (account vulnerable to asreproast attack)\s*$")
    notes = ""
    countFound = 0
    countPwn = 0
    countSuccess = 0
    cmeFound = False
    lsassy = False
    mode = ""
    ntds = []
    secrets = []
    tags = []
    lastValidDomain = None
    for line in cme_file:
        if isinstance(line, bytes):
            try:
                line = line.decode("utf-8", errors="ignore")
            except UnicodeDecodeError:
                result["success"] = False
                return result
                
        line=line.strip()
        line = remove_term_colors(line)
        # Search ip in file
        if line.startswith("SMB") or line.startswith("LDAP"):
            cmeFound = True
        if "Dumping LSA secrets" in line:
            mode = "lsa"
            continue
        elif "Dumped"  in line and "LSA secrets" in line:
            mode = ""
            continue
        elif "Dumping SAM hashes" in line:
            mode = "sam"
            continue
        elif "Added " in line and " SAM hashes" in line:
            mode = ""
            continue
        elif "Dumping the NTDS" in line:
            mode = "ntds"
            continue
        elif "Dumped " in line and "NTDS hashes" in line:
            mode = ""
            ntds = toAdd["ntds"]
            toAdd["type"] = "success"
            retour.append(toAdd)
            continue
        if mode == "":
            toAdd = {}
            if "LSASSY" in line and "Unable to dump lsass" not in line:
                lsassy = True
                res_lsassy = re.search(regex_module_lsassy, line)
                if res_lsassy is not None:
                    toAdd["type"] = "success"
                    toAdd["ip"] = res_lsassy.group(1)
                    toAdd["port"] = res_lsassy.group(2)
                    toAdd["machine_name"] = res_lsassy.group(3)
                    toAdd["domain"] = res_lsassy.group(4)
                    toAdd["username"] = res_lsassy.group(5)
                    password = res_lsassy.group(6)
                    if len(password) == 32:
                        try:
                            toAdd["hashNT"] = res_lsassy.group(6)
                        except:
                            toAdd["password"] = res_lsassy.group(6)
                    else:
                        toAdd["password"] = res_lsassy.group(6)
            else:
                res_infos = re.search(regex_info, line)
                res_asrep = re.search(regex_module_asproast, line)
                res_secrets = re.search(regex_module_secrets, line)
                if res_asrep is not None:
                    toAdd["type"] = "interesting"
                    toAdd["ip"] = res_asrep.group(1)
                    toAdd["port"] = res_asrep.group(2)
                    toAdd["machine_name"] = res_asrep.group(3)
                    toAdd["domain"] = res_asrep.group(4)
                    toAdd["username"] = res_asrep.group(5)
                    toAdd["reason"] = res_asrep.group(6).strip()
                    notes += f"ASREPROASTABLE USER FOUND: "+str(toAdd)
                
                if res_infos is not None:
                    toAdd["type"] = "info"
                    toAdd["ip"] = res_infos.group(1)
                    toAdd["port"] = res_infos.group(2)
                    toAdd["os"] = res_infos.group(3)
                    toAdd["machine_name"] = res_infos.group(4)
                    toAdd["domain"] = res_infos.group(5)
                    lastValidDomain = toAdd["domain"]
                    toAdd["signing"] = res_infos.group(6)
                    toAdd["smbv1"] = res_infos.group(7)
                    countFound += 1
                else:
                    success_infos = re.search(regex_success, line)
                    if success_infos is not None:
                        toAdd["type"] = "success"
                        toAdd["ip"] = success_infos.group(1)
                        toAdd["port"] = success_infos.group(2)
                        toAdd["machine_name"] = success_infos.group(3)
                        toAdd["domain"] = success_infos.group(4)
                        lastValidDomain = toAdd["domain"]
                        toAdd["username"] = success_infos.group(5)
                        toAdd["password"] = success_infos.group(6)
                        pwned = success_infos.group(7) != ""
                        toAdd["powned"] = pwned
                        if pwned:
                            countPwn += 1
                        else:
                            countSuccess += 1
                    elif res_secrets is not None:
                        toAdd["type"] = "success"
                        toAdd["ip"] = res_secrets.group(1)
                        toAdd["port"] = res_secrets.group(2)
                        toAdd["machine_name"] = res_secrets.group(3)
                        secret = res_secrets.group(4)
                        if secret and secret != "":
                            secrets.append(line)
                            if secret.startswith("$krb5asrep$"):
                                parts = secret.split("$")
                                try:
                                    data = parts[3]
                                    data_parts = data.split(":")[0].split("@")
                                    toAdd["username"] = "@".join(data_parts[0:-1])
                                    toAdd["domain"] = data_parts[-1]
                                    toAdd["secrets"] = [secret]
                                except IndexError as e:
                                    toAdd["secrets"] = toAdd.get("secrets", []) + [secret]
                    else:
                        failure_infos = re.search(regex_logon_failed, line)
                        if failure_infos is not None:
                            toAdd["type"] = "failure"
                            toAdd["ip"] = failure_infos.group(1)
                            toAdd["port"] = failure_infos.group(2)
                            toAdd["machine_name"] = failure_infos.group(3)
                            toAdd["domain"] = failure_infos.group(4)
                            toAdd["username"] = failure_infos.group(5)
                            #password is group 6 and its empty
                            toAdd["reason"] = failure_infos.group(7).strip()

            if toAdd.keys():
                retour.append(toAdd)
        
        if mode == "lsa" or mode == "sam":
            module_infos = re.search(regex_module_secrets, line)
            if module_infos is None:
                continue
            if toAdd.get("ip", None) is not None:
                if "toAdd" in locals():
                    if lastValidDomain is not None:
                        toAdd["domain"] = lastValidDomain
                    toAdd["secrets"] = toAdd.get("secrets", []) + [module_infos.group(4)]
            secrets.append(line)
        elif mode == "ntds":
            module_infos = re.search(regex_module_secrets, line)
            if module_infos is None:
                continue
            if "toAdd" in locals():
                if lastValidDomain is not None:
                    toAdd["domain"] = lastValidDomain
                toAdd["ip"] = module_infos.group(1)
                toAdd["port"] = module_infos.group(2)
                toAdd["machine_name"] = module_infos.group(3)
                toAdd["ntds"] = toAdd.get("ntds", []) + [module_infos.group(4)]
                
    if not cmeFound:
        result["success"] = False
        return result
    if lsassy:
        notes = f"CME LSASSY Success"
    notes = f"Pwn3d count : {countPwn}\nConnection success count : {countSuccess}\nHost found : {countFound}\nNTDS dump : {len(ntds)}\nSecrets found : {len(secrets)}\n"+ ("\n".join(secrets)) + notes
    result["retour"] = retour
    result["notes"] = notes
    result["countPwn"] = countPwn
    result["countSuccess"] = countSuccess
    result["success"] = True
    result["secrets"] = secrets
    result["lsassy"] = lsassy
    result["ntds"] = ntds
    result["tags"] = tags
    return result


def collectScopeIPs(pentest, hostsInfos, plugin_result):
    """
    Collect all the ips, ports, computers, users found after parsing the file into the PluginResult.
    Args:
        pentest: pentest identifier
        hostsInfos: the list of dictionaries with host info.
        plugin_result: PluginResult to collect into
    Returns:
        targets dict
    """
    targets = {}
    if hostsInfos is not None:
        for infos in hostsInfos:
            infosToAdd = {}
            users_to_add = []
            admins_to_add = []
            if infos["type"] == "info":
                thisOS = infos.get("os", "")
                if thisOS != "":
                    infosToAdd["os"] = thisOS
                machine_name = infos.get("machine_name", "")
                if machine_name != "":
                    infosToAdd["machine_name"] = machine_name
                SMBv1 = infos.get("smbv1", "")
                if SMBv1 != "":
                    infosToAdd["smbv1"] = SMBv1
                signing = infos.get("signing", "")
                if signing != "":
                    infosToAdd["signing"] = signing
                domain = infos.get("domain", "")
                if domain != "":
                    infosToAdd["domain"] = domain
            elif infos["type"] == "failure":
                if infos["reason"] in ["KDC_ERR_PREAUTH_FAILED", "KDC_ERR_CLIENT_REVOKED"]:
                    user_model = User(pentest).initialize(infos.get("domain"), infos.get("username"), None)
                    users_to_add.append(user_model)
            elif infos["type"] == "interesting":
                if "asreproast" in infos["reason"]:
                    user_info = infos
                    user_info["asreproastable"] = True
                    user_model = User(pentest).initialize(infos.get("domain"), infos.get("username"), infos=user_info)
                    users_to_add.append(user_model)
                    
            elif infos["type"] == "success":
                powned = infos.get("powned", False)
                user_info = infos
                secrets = infos.get("secrets", [])
                if secrets:
                    infosToAdd["secrets"] = infosToAdd.get("secrets", []) + secrets
                    user_info["secrets"] = secrets
                ntds = infos.get("ntds", [])
                if ntds:
                    del infos["ntds"]
                    infosToAdd["ntds"] = ntds
                    regex_ntds = re.compile(r"^\s*(\S+):\d+:([a-f0-9]+):([a-f0-9]+):::\s*$")
                    for line in ntds:
                        matched = re.search(regex_ntds, line)
                        if matched:
                            username = matched.group(1)
                            this_info = {}
                            hashLM = matched.group(2)
                            hashNT = matched.group(3)
                            if hashLM != "aad3b435b51404eeaad3b435b51404ee":
                                this_info["hashLM"] = hashLM
                            this_info["hashNT"] = hashNT
                            user_model = User(pentest).initialize(infos.get("domain", ""), username, "", infos=this_info)
                            users_to_add.append(user_model)
                hashNT = infos.get("hashNT", "")
                if hashNT != "":
                    user_info["hashNT"] = hashNT
                user_model = User(pentest).initialize(infos.get("domain", ""), infos.get("username", ""), infos.get("password"), infos=user_info)
                users_to_add.append(user_model)
                if powned:
                    infosToAdd["powned"] = powned
                    admins_to_add.append(user_model)

            host = str(infos["ip"])
            port = str(infos["port"])
            proto = "tcp"
            service = "netbios-ssn"

            plugin_result.ips.append(Ip(pentest).initialize(host, infos={"plugin": CME.get_name(), "hostname": infos.get("machine_name", "")}))
            plugin_result.ports.append(Port(pentest).initialize(host, port, proto, service, infos={"plugin": CME.get_name()}))

            port_key = {"ip": host, "port": port, "proto": proto}

            if infos["type"] == "success":
                if infos.get("powned", False):
                    plugin_result.tag_additions.append(TagAddition(
                        collection="ips", db_key={"ip": host},
                        tag=Tag("pwned", "red", "high", notes=str(infos))
                    ))
                    plugin_result.tag_additions.append(TagAddition(
                        collection="ports", db_key=port_key,
                        tag=Tag("pwned", "red", "high", notes=str(infos))
                    ))

            # Collect users and admins as deferred UserLink operations
            for user in users_to_add:
                if isinstance(user, User):
                    plugin_result.users.append(user)
                    plugin_result.user_links.append(UserLink(
                        computer_ip=host,
                        domain=infos.get("domain", ""),
                        username=user.username,
                        password=user.password if hasattr(user, 'password') else "",
                        infos=user.infos if hasattr(user, 'infos') else None,
                        is_admin=False
                    ))
                    # Deferred user tags
                    if hasattr(user, 'infos') and user.infos:
                        user_key = {"username": user.username, "domain": user.domain if hasattr(user, 'domain') else infos.get("domain", "")}
                        if user.infos.get("asreproastable", False):
                            plugin_result.tag_additions.append(TagAddition(
                                collection="users", db_key=user_key,
                                tag=Tag("asreproastable", color="orange", level="high", notes=f"{user.domain}\\{user.username} is asreproastable")
                            ))
                        if user.infos.get("secrets", []):
                            plugin_result.tag_additions.append(TagAddition(
                                collection="users", db_key=user_key,
                                tag=Tag("user-secrets-found", color="red", level="high", notes=f"{user.domain}\\{user.username} has secrets : {user.infos.get('secrets')}")
                            ))
                        if user.infos.get("hashLM", "") != "":
                            plugin_result.tag_additions.append(TagAddition(
                                collection="users", db_key=user_key,
                                tag=Tag("hashLM-found", color="red", level="high", notes=f"{user.domain}\\{user.username} has hashLM : {user.infos.get('hashLM')}")
                            ))
                        if user.infos.get("hashNT", "") != "":
                            plugin_result.tag_additions.append(TagAddition(
                                collection="users", db_key=user_key,
                                tag=Tag("hashNT-found", color="red", level="high", notes=f"{user.domain}\\{user.username} has hashNT : {user.infos.get('hashNT')}")
                            ))

            for user in admins_to_add:
                if isinstance(user, User):
                    plugin_result.user_links.append(UserLink(
                        computer_ip=host,
                        domain=user.domain if hasattr(user, 'domain') else infos.get("domain", ""),
                        username=user.username,
                        password=user.password if hasattr(user, 'password') else "",
                        is_admin=True
                    ))

            # Deferred computer update
            plugin_result.object_updates.append(ObjectUpdate(
                collection="computers",
                db_key={"ip": host},
                data={
                    "name": infos["machine_name"],
                    "domain": infos.get("domain", ""),
                    "infos": {**infosToAdd, "plugins": CME.get_name()}
                }
            ))

            # Deferred computer tags for signing/smbv1
            if str(infosToAdd.get("signing", True)).lower() == "false":
                plugin_result.tag_additions.append(TagAddition(
                    collection="computers", db_key={"ip": host},
                    tag=Tag("signing-disabled", "orange", "medium", f"Signing is disabled on {infos['machine_name']}")
                ))
            if str(infosToAdd.get("smbv1", False)).lower() == "true":
                plugin_result.tag_additions.append(TagAddition(
                    collection="computers", db_key={"ip": host},
                    tag=Tag("smbv1-enabled", "orange", "medium", f"SMBv1 is enabled on {infos['machine_name']}")
                ))

            # Port info updates (without users/admins)
            port_infos = {k: v for k, v in infosToAdd.items() if k not in ("users", "admins")}
            if port_infos:
                plugin_result.info_updates.append(InfoUpdate(
                    collection="ports", db_key=port_key, infos=port_infos
                ))
            targets["cme_" + host + "_" + port] = {
                    "ip": host, "port": port, "proto": proto}
    return targets

class CME(Plugin):
    """Inherits Plugin
    A plugin to parse a crackmapexec scan"""
    default_bin_names = ["cme", "crackmapexec"]
    def getFileOutputArg(self):
        """Returns the command line paramater giving the output file
        Returns:
            string
        """
        return " | tee "

    def getFileOutputExt(self):
        """Returns the expected file extension for this command result file
        Returns:
            string
        """
        return ".log.txt"

    def getFileOutputPath(self, commandExecuted):
        """Returns the output file path given in the executed command using getFileOutputArg
        Args:
            commandExecuted: the command that was executed with an output file inside.
        Returns:
            string: the path to file created
        """
        return commandExecuted.split(self.getFileOutputArg())[-1].strip().split(" ")[0]

    def getTags(self):
        """Returns a list of tags that can be added by this plugin
        Returns:
            list of strings
        """
        return {"pwned-cme" : Tag("pwned-cme", "red", "high"), 
                "info-cme-connection-success": Tag("info-cme-connection-success", "green", "info"),
                "todo-cme-secrets-found": Tag("todo-cme-secrets-found", "red", "todo"),
                "todo-lsassy-success": Tag("todo-lsassy-success", "red", "todo"),
                "user-secrets-found": Tag("user-secrets-found", "red", "high"),
                "asreproastable": Tag("asreproastable", "orange", "high"),
                "pwned": Tag("pwned", "red", "high"),
                "signing-disabled": Tag("signing-disabled", "orange", "medium"),
                "smbv1-enabled" : Tag("smbv1-enabled", "orange", "medium"),
                "pwned-ntds": Tag("pwned-ntds", "black", "critical"),
                "hashLM-found": Tag("hashLM-found", "red", "high")}


    def Parse(self, pentest, file_opened, **kwargs):
        """
        Parse a opened file to extract information
       
        Args:
            file_opened: the open file
            kwargs: not used
        Returns:
            PluginResult
        """
        tags = []
        result = getInfos(file_opened)
        if result.get("success", False) == False:
            return PluginResult.empty()
        hostsInfos = result.get("retour", [])
        if result.get("countPwn") is not None:
            count = int(result.get("countPwn"))
            if count > 0:
                tags += [Tag(self.getTags()["pwned-cme"], notes=f"{count} hosts pwned")]
        if result.get("countSuccess") is not None:
            count = int(result.get("countSuccess"))
            if count > 0:
                tags += [Tag(self.getTags()["info-cme-connection-success"], notes=f"{count} hosts connected")]
            if len(result.get("secrets",[])) > 0:
                tags += [Tag(self.getTags()["todo-cme-secrets-found"], notes=f"{len(result.get('secrets',[]))} secrets found")]
            if result.get("lsassy"):
                tags += [Tag(self.getTags()["todo-lsassy-success"], notes=f"lsassy success")]
            if len(result.get("ntds", [])) > 0:
                tags += [Tag(self.getTags()["pwned-ntds"], notes=f"{len(result.get('ntds',[]))} ntds found")]
        if hostsInfos is None:
            return PluginResult.empty()
        plugin_result = PluginResult(notes=result.get("notes", ""), tags=tags, lvl="ports")
        targets = collectScopeIPs(pentest, hostsInfos, plugin_result)
        plugin_result.targets = targets
        return plugin_result
